apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-dijon-fr
  labels:
    app: nginx
    az:  dijon-fr
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-dijon-fr
        image: nginx
        ports:
        - containerPort: 80
      nodeSelector:
        az: dijon-fr
