apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-nginx
spec:
  selector:
    app: nginx
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31200
